language: node_js
dist: bionic

node_js:
  - "12"
  # - "stable"
  # - "latest"

cache: ccache
before_install:
- PATH=$PATH:$HOME/bin
script:
- npm i
- npm i -g typescript
- tsc
- npm run test
after_success:
  - ./dev/publish.sh
env:
  matrix:
    - PLATFORM="native_static"
    - PLATFORM="native_dyn"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - python3-pip
      - libbz2-dev
      - ccache
      - zlib1g-dev
      - uuid-dev
# matrix:
#   include:
#     - env: PLATFORM="native_dyn"
#       os: osx
