language: node_js

node_js:
  - "6.0"
  - "stable"
  - "latest"

before_install:
- PATH=$PATH:$HOME/bin
install: travis/install_deps.sh

env:
  - CC=gcc-4.8 CXX=g++-4.8
  - CC=echo CXX=echo

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

os:
  - linux
  - osx